title: Lionel TAILHARDAT
url: "https://github.com/GenEars"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_text: "Powered by Jekyll and \"researcher\" by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index"
 - name: "Research Projects and Activities"
   link: "research"
 - name: "Publications"
   link: "publications"
 - name: "Teaching"
   link: "teaching"

# Plugins
plugins:
 - jekyll-paginate
 - jekyll-sitemap
 - jekyll-gist
 - jekyll-feed
 - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
 - jekyll-paginate
 - jekyll-sitemap
 - jekyll-gist
 - jekyll-feed
 - jemoji

# Site Author
author:
  name             : "Lionel Tailhardat"
  avatar           : "me.jpg"
  bio              : "AI Researcher and Project Manager"
  location         : "Chatillon, France"
  employer         : "Orange"
  pubmed           :
  googlescholar    : "https://scholar.google.com/citations?user=L3-8tGYAAAAJ"
  email            :
  researchgate     :
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "GenEars"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      :
  lastfm           :
  linkedin         : "lionel-tailhardat-566510120"
  orcid            : "https://orcid.org/0000-0001-5887-899X"
  pinterest        :
  soundcloud       :
  stackoverflow    :
  steam            :
  tumblr           :
  twitter          : "TailhardatL"
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :