title: Lionel TAILHARDAT
url: "https://github.com/GenEars"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_text: "Powered by Jekyll and \"researcher\" by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index"
 - name: "Research Projects and Activities"
   link: "research"
 - name: "Publications"
   link: "publications"
 - name: "Teaching"
   link: "teaching"

# Plugins
plugins:
 - jekyll-paginate
 - jekyll-sitemap
 - jekyll-gist
 - jekyll-feed
 - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
 - jekyll-paginate
 - jekyll-sitemap
 - jekyll-gist
 - jekyll-feed
 - jemoji
